/**
 * Shared logic for the two Scaffolded Learning modules — Take Test Mastery and
 * Review Materials. Used by `student/remediation.tsx` and the class screen's
 * Modules tab, which present the same two things in different places.
 *
 * Port of activklass-web/src/routes/student/scaffolding.js. The web file
 * carries theme colours inside BUCKETS; here each bucket names a colour ROLE
 * instead so the class-based palette can paint it in either theme. Every
 * label, threshold and sentence is the web's, word for word — a student
 * reading "Developing · 76%" on a laptop must read the same on their phone.
 * Edit one, edit the other.
 *
 * MASTERY IS DERIVED, NEVER STORED. A topic's mastery is the student's best
 * attempt percentage across the quizzes linked to that topic. That is the whole
 * mechanism behind "take the remediation quiz and your mastery updates" — a new
 * attempt changes what this calculation returns, so nothing has to be written
 * back. It also means mastery can never drift out of sync with the attempts it
 * claims to summarise.
 */

/** An attempt at or above this counts as mastered for that student. */
export const PASS = 75;
const NEEDS_BELOW = 60;
const DEVELOPING_BELOW = 80;

export type Bucket = 'none' | 'needs' | 'developing' | 'mastered';

export interface Resource {
  id?: string;
  _key?: string;
  title?: string;
  resource_type?: 'file' | 'link' | 'rich_text' | string;
  url?: string | null;
  content_markdown?: string | null;
}

export interface Topic {
  id?: string;
  title?: string;
  learning_objectives?: string[];
  objectives?: string[];
  resources?: Resource[];
}

export interface Module {
  id?: string;
  title?: string;
  description?: string;
  published?: boolean;
  topics?: Topic[];
}

export interface Syllabus {
  modules?: Module[];
  [key: string]: unknown;
}

export interface MasteryQuiz {
  id: string;
  title?: string;
  status?: string;
  topic_id?: string | null;
  questions?: { points?: unknown }[];
  total_possible?: unknown;
  assigned_to?: 'all' | string[] | null;
  [key: string]: unknown;
}

export interface MasteryAttempt {
  id?: string;
  total_score?: number | null;
  [key: string]: unknown;
}

export type AttemptsByQuiz = Record<string, MasteryAttempt[]>;

export interface Mastery {
  pct: number | null;
  attempts: number;
  bucket: Bucket;
  quizzes: MasteryQuiz[];
}

export function quizTotalPoints(quiz: MasteryQuiz | null | undefined): number {
  const summed = (quiz?.questions ?? []).reduce((s, q) => s + (Number(q.points) || 0), 0);
  // Remediation quizzes generated by AI sometimes carry total_possible without
  // per-question points; fall back rather than dividing by zero and hiding them.
  return summed || Number(quiz?.total_possible) || 0;
}

export function bucketOf(pct: number | null | undefined): Bucket {
  if (pct == null) return 'none';
  if (pct < NEEDS_BELOW) return 'needs';
  if (pct < DEVELOPING_BELOW) return 'developing';
  return 'mastered';
}

/** Label plus the colour role the palette paints it with. */
export const BUCKETS: Record<Bucket, { label: string; tone: 'faint' | 'danger' | 'warning' | 'success' }> = {
  none: { label: 'Not attempted', tone: 'faint' },
  needs: { label: 'Needs work', tone: 'danger' },
  developing: { label: 'Developing', tone: 'warning' },
  mastered: { label: 'Mastered', tone: 'success' },
};

/** Quizzes wired to a syllabus topic. `topic_id` is the only link that exists. */
export function quizzesForTopic(topicId: string | null | undefined, quizzes: MasteryQuiz[] = []): MasteryQuiz[] {
  return topicId ? quizzes.filter((q) => q.topic_id === topicId) : [];
}

/**
 * The student's own mastery of one topic.
 * Returns pct = null when they have no scored attempt yet — which is different
 * from 0%, and is shown differently.
 */
export function topicMastery(
  topicId: string | null | undefined,
  quizzes: MasteryQuiz[] = [],
  attemptsByQuiz: AttemptsByQuiz = {}
): Mastery {
  return masteryOf(quizzesForTopic(topicId, quizzes), attemptsByQuiz);
}

/**
 * The quizzes a remediation offers as its mastery test: every quiz linked to
 * its topic, plus the one the teacher attached to the plan itself —
 * `recommended_quiz_id`, which the publish path writes onto each student's
 * copy. That quiz may carry a different topic_id, or none (the plan's topic
 * can be null too), and the topic-only lookup never showed it.
 */
export function remediationQuizzes(
  r: { topic_id?: string | null; recommended_quiz_id?: string | null } | null | undefined,
  quizzes: MasteryQuiz[] = []
): MasteryQuiz[] {
  const linked = quizzesForTopic(r?.topic_id, quizzes);
  const pinned = r?.recommended_quiz_id ? quizzes.find((q) => q.id === r.recommended_quiz_id) : null;
  if (pinned && !linked.some((q) => q.id === pinned.id)) return [pinned, ...linked];
  return linked;
}

/** Mastery over an explicit set of quizzes. Best scored attempt wins. */
export function masteryOf(linked: MasteryQuiz[] = [], attemptsByQuiz: AttemptsByQuiz = {}): Mastery {
  let best: number | null = null;
  let attempts = 0;

  for (const q of linked) {
    const total = quizTotalPoints(q);
    if (!total) continue;
    for (const a of attemptsByQuiz[q.id] ?? []) {
      if (a.total_score == null) continue; // still being marked, or still open
      attempts += 1;
      const pct = (a.total_score / total) * 100;
      if (best == null || pct > best) best = pct;
    }
  }

  const pct = best == null ? null : Math.round(best);
  return { pct, attempts, bucket: bucketOf(pct), quizzes: linked };
}

/**
 * A quiz reaches a student if it is assigned to everyone ('all', or a legacy
 * undefined) or names them. Shared so the class screen and the remediation
 * screen cannot disagree about which quizzes a student is allowed to see.
 */
export function assignedToStudent(quiz: MasteryQuiz | null | undefined, studentId: string): boolean {
  const a = quiz?.assigned_to;
  return !a || a === 'all' || (Array.isArray(a) && a.includes(studentId));
}

/** The teacher's scaffolds page titles these `Remediation · <topic>`. */
export function isRemediationQuiz(quiz: MasteryQuiz | null | undefined): boolean {
  return typeof quiz?.title === 'string' && quiz.title.startsWith('Remediation ·');
}

export interface FoundTopic {
  topic: Topic;
  module: Module;
  moduleNo: number;
  topicNo: number;
}

/**
 * Walk a syllabus for one topic, and hand back its module for context.
 *
 * The positions are 1-based and count only what the student can see: the
 * syllabus reaching this code has already had unpublished modules filtered
 * out (`loadSyllabus`), so "Module 2" here is the second module on the
 * student's Modules tab, not the second one the teacher typed.
 */
export function findTopic(syllabus: Syllabus | null | undefined, topicId: string | null | undefined): FoundTopic | null {
  if (!syllabus || !topicId) return null;
  const modules = syllabus.modules ?? [];
  for (let mi = 0; mi < modules.length; mi++) {
    const m = modules[mi];
    const topics = m.topics ?? [];
    for (let ti = 0; ti < topics.length; ti++) {
      const t = topics[ti];
      if (t.id === topicId) return { topic: t, module: m, moduleNo: mi + 1, topicNo: ti + 1 };
    }
  }
  return null;
}

export interface TopicLocation extends FoundTopic {
  moduleLabel: string;
  moduleTitle: string;
  topicLabel: string;
  topicTitle: string;
  resourceCount: number;
}

/**
 * Where a scaffolded topic sits in the teacher's modules, in the words the
 * Modules tab uses: a module, and a sub-module inside it (the tab calls a
 * `topic` a sub-module; there is no separate lecture level in a syllabus).
 *
 * Returns null when the topic is not in the published modules — the caller
 * decides what to say, because "not linked" and "no longer published" are
 * different situations and both already have wording on the card.
 */
export function topicLocation(syllabus: Syllabus | null | undefined, topicId: string | null | undefined): TopicLocation | null {
  const found = findTopic(syllabus, topicId);
  if (!found) return null;
  return {
    ...found,
    moduleLabel: `Module ${found.moduleNo}`,
    moduleTitle: found.module.title || `Module ${found.moduleNo}`,
    topicLabel: `Sub-module ${found.topicNo}`,
    topicTitle: found.topic.title || `Sub-module ${found.topicNo}`,
    resourceCount: (found.topic.resources ?? []).length,
  };
}

/**
 * The route params that open the class screen on the Modules tab with one
 * sub-module in view. The web builds a URL (`?tab=topics&topic=`); expo-router
 * takes the same two keys as params, and the class screen reads both because
 * the tab is not mounted until chosen.
 */
export function topicRoute(classId: string, topicId?: string | null) {
  const params: Record<string, string> = { tab: 'topics' };
  if (topicId) params.topic = topicId;
  return { pathname: `/student/class/${classId}`, params };
}

export interface ResourceState {
  available: boolean;
  reason?: string;
}

/**
 * Whether a learning resource can actually be opened.
 *
 * A `file` resource carries the download URL the syllabus page got back from
 * Storage (live since 2026-09-12, on Blaze). One saved before that date, or
 * whose upload failed, has no URL and no object behind it, so the link would
 * be dead. Saying why is more use to a student than a link that fails, and it
 * stops them assuming the material is missing from the course.
 */
export function resourceState(res: Resource | null | undefined): ResourceState {
  switch (res?.resource_type) {
    case 'file':
      return res.url
        ? { available: true }
        : { available: false, reason: 'This file was never uploaded, so it cannot be opened here. Ask your teacher for a copy.' };
    case 'link':
      return res.url
        ? { available: true }
        : { available: false, reason: 'No address was saved for this link.' };
    case 'rich_text':
      return res.content_markdown?.trim()
        ? { available: true }
        : { available: false, reason: 'This study note has not been written yet.' };
    default:
      return { available: false, reason: 'This resource type is not supported yet.' };
  }
}

export const RESOURCE_META: Record<string, { icon: string; label: string }> = {
  file: { icon: '📄', label: 'File' },
  link: { icon: '🔗', label: 'Link' },
  rich_text: { icon: '✍️', label: 'Study note' },
};

/**
 * A study note is written in Markdown for the web's renderer. The app has no
 * Markdown component (adding one is a dependency, which needs owner approval),
 * so the note is shown as plain text with the markup removed rather than with
 * asterisks and hashes left in. Structure is kept as line breaks.
 */
export function markdownToPlain(text: string | null | undefined): string {
  if (!text) return '';
  return text
    .replace(/```[\s\S]*?```/g, (block) => block.replace(/```\w*\n?/g, ''))
    .replace(/^[ \t]{0,3}#{1,6}[ \t]+/gm, '')
    .replace(/^[ \t]*>[ \t]?/gm, '')
    .replace(/^[ \t]*[-*+][ \t]+/gm, '• ')
    .replace(/!\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '$1 ($2)')
    .replace(/(\*\*|__)(.*?)\1/g, '$2')
    .replace(/(\*|_)(.*?)\1/g, '$2')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}
