import React, { useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, ScrollView, SafeAreaView, ActivityIndicator } from 'react-native';
import { useRouter } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { normaliseCode } from '../../src/lib/parent';

// Six characters from the backend's SHARE_CODE_ALPHABET (app/models/identity.py),
// which omits O/0/I/1 because these codes get read aloud and copied by hand.
const CODE_PATTERN = /^[A-HJ-NP-Z2-9]{6}$/;

export default function ParentRegisterCodeScreen() {
  const router = useRouter();
  
  const [code, setCode] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleVerifyCode = async () => {
    if (!code.trim()) {
      setError('Please enter the invitation code.');
      return;
    }

    setLoading(true);
    setError(null);

    /* Format check only.
       Redeeming a code requires an authenticated parent account (the backend
       gates /api/guardian-links/redeem on the parent role), so the code cannot
       be looked up before sign-up. It is verified for real on the next screen,
       right after the account is created. The old version queried
       consent_records straight from the device — that collection no longer
       drives linking, and an unauthenticated client cannot read it anyway. */
    const cleaned = normaliseCode(code);
    if (!CODE_PATTERN.test(cleaned)) {
      setError(
        'That code does not look right. It is 6 characters — letters and numbers, no O, 0, I or 1.'
      );
      setLoading(false);
      return;
    }

    router.push({ pathname: '/parent/details', params: { inviteCode: cleaned } });
    setLoading(false);
  };

  return (
    <SafeAreaView className="flex-1 bg-slate-950">
      <StatusBar style="light" />
      <ScrollView contentContainerStyle={{ flexGrow: 1 }} className="px-6 py-10 justify-between">
        
        {/* Back Button */}
        <TouchableOpacity 
          onPress={() => router.back()} 
          className="self-start w-10 h-10 items-center justify-center bg-slate-900 border border-slate-800 rounded-xl"
        >
          <Text className="text-white text-lg font-bold">←</Text>
        </TouchableOpacity>

        {/* Central Card */}
        <View className="my-auto">
          {/* Header */}
          <View className="mb-8">
            <Text className="text-white text-3xl font-extrabold font-sans">
              Parent Connection
            </Text>
            <Text className="text-slate-400 text-sm mt-2 font-sans">
              Enter the unique invitation code generated by your child from their student portal profile.
            </Text>
          </View>

          {/* Form */}
          <View className="space-y-4">
            
            {/* Error Message */}
            {error && (
              <View className="bg-red-500/10 border border-red-500/30 p-4 rounded-2xl mb-4">
                <Text className="text-red-400 text-xs font-semibold leading-relaxed">
                  {error}
                </Text>
              </View>
            )}

            {/* Code Input */}
            <View>
              <Text className="text-slate-300 text-xs font-bold mb-2 uppercase tracking-wider">
                Invitation Code
              </Text>
              <TextInput
                value={code}
                onChangeText={setCode}
                placeholder="e.g. XY89Z2"
                placeholderTextColor="#64748b"
                autoCapitalize="characters"
                maxLength={10}
                className="w-full bg-slate-900 border border-slate-850 p-4 rounded-xl text-white text-center text-lg font-bold focus:border-indigo-500"
              />
            </View>

            {/* Continue Button */}
            <TouchableOpacity
              onPress={handleVerifyCode}
              disabled={loading}
              activeOpacity={0.8}
              className="w-full bg-indigo-600 py-4 rounded-xl items-center justify-center mt-6"
            >
              {loading ? (
                <ActivityIndicator size="small" color="#ffffff" />
              ) : (
                <Text className="text-white text-base font-bold font-sans">
                  Verify &amp; Continue
                </Text>
              )}
            </TouchableOpacity>

          </View>
        </View>

        {/* Guidance Footer */}
        <View className="bg-slate-900/40 border border-slate-800/60 p-4 rounded-2xl">
          <Text className="text-slate-400 text-xs leading-relaxed text-center">
            💡 <Text className="font-semibold text-slate-300">How to get the code:</Text> Have your child sign in to the ActivKlass app on their device, open their <Text className="text-indigo-400">Profile</Text>, and copy the alphanumeric code under <Text className="text-indigo-400">Parental Access</Text>.
          </Text>
        </View>

      </ScrollView>
    </SafeAreaView>
  );
}
